banner:
  enabled: true

storage:
  type: SQLITE # or MYSQL # Tùy bạn muốn sài gì

mysql:
  host: localhost
  port: 3306
  database: gems
  username: root
  password: password

auto-save:
  delay-seconds: 5
  console-log: true

language: vi
