name: CrystalEngine
main: aoi.aoichan.AoiMain
version: 1.0.0
api-version: 1.21
author: AoiChan
description: Core Engine cho hệ thống Crystal plugins

commands:
  crystal:
    description: CrystalEngine Command
