name: GemsUltimate
version: 2.1.0
main: aoichan.crystal.AoiMain
api-version: 1.20
author: AoiDev

commands:
  gems:
    description: Main command
    usage: /gems
    permission: gems.admin

permissions:
  gems.admin:
    default: op
