name: ◡🥀𝓐𝓸𝓲𝓒𝓱𝓪𝓷🥀◡【👻】

# Bật/tắt upload Artifact ( .jar )
env:
  ENABLE_ARTIFACT: false

on:
  push:
    branches:
      - main

  pull_request:
    
  workflow_dispatch:

permissions:
  actions: write
  contents: read
  
jobs:
  aoichan:
    name: ◡🥀𝓐𝓸𝓲𝓒𝓱𝓪𝓷🥀◡
    runs-on: ubuntu-latest
    
    steps:
      - name: 🔎𝓒𝓱𝓮𝓬𝓴 𝓢𝓸𝓾𝓻𝓬𝓮
        uses: actions/checkout@v6
        with:
          lfs: true

      # Cài đặt JavaScript
      - name: ☕ ｊａｖａＳcｒ𝚒ｐ𝚝
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle


      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Clean Project
        run: ./gradlew clean

      - name: Compile Project
        run: ./gradlew compileJava --stacktrace

      - name: Run Tests
        run: ./gradlew test --stacktrace
        continue-on-error: false

      - name: Build ShadowJar
        run: ./gradlew shadowJar --stacktrace

      - name: Verify Artifact Exists
        run: |
          ls -lah build/libs/
          test -f build/libs/Cultivation-1.0.0-SNAPSHOT.jar

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Cultivation
          path: build/libs/*.jar
          if-no-files-found: error

      #- name: 🛡️ Security Check
        #run: |
          #mvn org.owasp:dependency-check-maven:check \
            #-DnvdApiKey=${{ secrets.NVD_API_KEY }}
        #env:
          #GH_TOKEN: ${{ secrets.AOI_ACTIONS }}

      # Đóng gói file .jar
      - name: 📦 𝓤𝓹𝓵𝓸𝓪𝓻𝓭 𝓳𝓪𝓻
        if: ${{ env.ENABLE_ARTIFACT == 'true' }}
        uses: actions/upload-artifact@v5
        with:
          name: Cultivation
          path: build/libs/*.jar

      # Tự động dọn dẹp Workflows Runs 【 5 Runs 】
      - name: ♻️𝐎𝐋𝐃 𝐖𝐎𝐑𝐊𝐅𝐋𝐎𝐖𝐒
        run: |
          gh api repos/${{ github.repository }}/actions/runs \
            --paginate \
            --jq '.workflow_runs | sort_by(.created_at) | reverse | .[5:] | map(select(.status=="completed")) | .[].id' \
            | while read run; do
                echo "🗑️ đã xóa $run"
                gh api repos/${{ github.repository }}/actions/runs/$run -X DELETE
              done
        env:
          GH_TOKEN: ${{ secrets.AOI_ACTIONS }}

      - name: ♻️𝐎𝐋𝐃 𝐂𝐀𝐂𝐇𝐄
        run: |
          gh cache list --json id,createdAt \
            | jq 'sort_by(.createdAt) | reverse | .[5:] | .[].id' \
            | while read id; do
                echo "🗑️ đã xóa $id"
                gh cache delete "$id"
              done
        env:
          GH_TOKEN: ${{ secrets.AOI_ACTIONS }} 
