name: 🍀𝓐𝓸𝒾𝒞𝒽𝒶𝓃💋 ➪【Crystal💎】

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "pom.xml"
      - ".github/workflows/**"

  pull_request:
    paths:
      - "src/**"
      - "pom.xml"
      - ".github/workflows/**"

jobs:
  build:
    name: 【💋𝓐𝓸𝓲𝓒𝓱𝓪𝓷👅】
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read

    steps:
      - name: 【🔎Kiểm tra】
        uses: actions/checkout@v4

      # Cài đặt Actions Node.js
      - name: 【🟢🅽🅾🅳🅴】
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # Cài đặt JavaScript
      - name: 【☕🅹🅰🆅🅰】
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Xây dựng cấu trúc
      - name: 【📦🅱🆄🅸🅻🅳🏗️】
        run: mvn -B package -DskipTests

      # Đóng gói thành file .jar
      - name: 【📦🅹🅰🆁】
        uses: actions/upload-artifact@v4
        with:
          name: Crystal-Core
          path: target/*.jar
          retention-days: 1

      # Tự động dọn dẹp Workflows Runs
      - name: 【🗑️Dọn Dẹp】
        if: success()
        run: |
          echo "Dọn dẹp Workflows Runs..."

          runs=$(gh api repos/${{ github.repository }}/actions/runs \
          --paginate --jq '.workflow_runs[].id')

          count=0
          for run in $runs; do
            count=$((count+1))
            if [ $count -gt 5 ]; then
              echo "Deleting run $run"
              gh api repos/${{ github.repository }}/actions/runs/$run -X DELETE
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
